#!/bin/bash

# author settings
AUTHOR="Björn Hempel"
EMAIL="bjoern@hempel.li"

# declare parameter list array
PARAMETERS=()

# default parameter
MARKDOWN_OUTPUT=true
JSON_OUTPUT=false
HTML_OUTPUT=false
COMPRESS_JSON=false
SHOW_SYSTEM_INFORMATIONS=false
SHOW_LINKS=false
SHOW_SSL_CERTIFICATES=false
SHOW_DOMAIN_LIST=false
DOCKER_NAME=""
PARSE_VHOSTS=true
OUTPUT_TARGET=""
OUTPUT_NAME="index"
CREATE_JSON=false
CREATE_MARKDOWN=true
CREATE_HTML=false
MARKDOWN_SUFFIX="md"
JSON_SUFFIX="json"
HTML_SUFFIX="html"
SILENCE=false
ONLY_LIST_DOMAINS=false
INSTALL_LIVE_VIEW=false

# read arguments
# help:
# help: An apache host viewer (%version%) by %author% <%email%>.
# help:
# help: Usage: %scriptname% [options...]
while [[ $# > 0 ]]; do
    case "$1" in
        # help:  -h,    --help                    Shows this help.
        -h|--help)
            version=$(getRepositoryVersion "$pathRoot" true)
            cat "$BASH_SOURCE" | grep "# help:" | grep -v 'cat parameter' | sed 's/[ ]*# help:[ ]\?//g' | \
                sed "s~%scriptname%~$scriptname~g" | \
                sed "s~%version%~$version~g" | \
                sed "s~%author%~$AUTHOR~g" | \
                sed "s~%email%~$EMAIL~g"
            exit 0
            ;;

        # help:  -v,    --version                 Shows the version number.
        -v|--version)
            version=$(getRepositoryVersion "$pathRoot")
            echo "$version"
            exit 0
            ;;

        # help:
        # help:  -l,    --only-list-domains       Only list the domains, that are available on this system.
        -l|--only-list-domains)
            ONLY_LIST_DOMAINS=true
            ;;

        # help:
        # help:  -m,    --markdown                Shows the output as markdown and disable all other output types (json, html) - default output
        -m|--markdown)
            MARKDOWN_OUTPUT=true
                JSON_OUTPUT=false
                HTML_OUTPUT=false
            ;;

        # help:  -j,    --json                    Shows the output as json and disable all other output types (markdown, html)
        -j|--json)
            MARKDOWN_OUTPUT=false
                JSON_OUTPUT=true
                HTML_OUTPUT=false
            ;;

        # help:         --html                    Shows the output as html and disable all other output types (markdown, json)
        --html)
            MARKDOWN_OUTPUT=false
                JSON_OUTPUT=false
                HTML_OUTPUT=true
            ;;

        # help:         --compress-json           Compress the outputted json.
        --compress-json)
            COMPRESS_JSON=true
            ;;

        # help:
        # help:         --output-target           Writes also the result into this target folder.
        --output-target)
            OUTPUT_TARGET="$2"
            shift
            ;;
        --output-target=*)
            OUTPUT_TARGET="${1#*=}"
            ;;

        # help:         --output-name             Set the output name (default is "index").
        --output-name)
            OUTPUT_NAME="$2"
            shift
            ;;
        --output-name=*)
            OUTPUT_NAME="${1#*=}"
            ;;

        # help:         --create-markdown         Creates a markdown file (--output-target must be set).
        --create-markdown)
            CREATE_MARKDOWN=true
            ;;
        --create-markdown=*)
            [ "${1#*=}" == "0" ] && CREATE_MARKDOWN=false || CREATE_MARKDOWN=true
            ;;

        # help:         --create-json             Creates a json file (--output-target must be set).
        --create-json)
            CREATE_JSON=true
            ;;
        --create-json=*)
            [ "${1#*=}" == "0" ] && CREATE_JSON=false || CREATE_JSON=true
            ;;

        # help:         --create-html             Creates a html file (--output-target must be set).
        --create-html)
            CREATE_HTML=true
            ;;
        --create-html=*)
            [ "${1#*=}" == "0" ] && CREATE_HTML=false || HTML_MARKDOWN=true
            ;;

        # help:
        # help:  -i,    --install-live-view       Installs the live view api.
        -i|--install-live-view)
             INSTALL_LIVE_VIEW=true
             ;;

        # help:
        # help:  -s,    --show-system-info        Shows system informations.
        -s|--show-system-info)
            SHOW_SYSTEM_INFORMATIONS=true
            ;;

        # help:         --show-links              Shows links inside the markdown and html file.
        --show-links)
            SHOW_LINKS=true
            ;;

        # help:         --show-ssl-certificates   Shows the ssl certificates.
        --show-ssl-certificates)
            SHOW_SSL_CERTIFICATES=true
            ;;

        # help:         --show-domain-list        Shows a separated domain list.
        --show-domain-list)
            SHOW_DOMAIN_LIST=true
            ;;

        # help:
        # help:  -d,    --docker-container        Checks a docker machine instead of the local machine.
        -d|--docker-container)
            DOCKER_NAME="$2"
            shift
            ;;
        -d=*|--docker-container=*)
            DOCKER_NAME=("${1#*=}")
            ;;

        # help:
        # help:         --disable-vhost-parser    Disable the vhost parser.
        --disable-vhost-parser)
            PARSE_VHOSTS=false
            ;;

        # help:
        # help:         --silence                 Disable the output.
        --silence)
            SILENCE=true
            ;;

        # help:
        #
        # collect all unknown parameters
        #
        *)
            PARAMETERS+=("$1")
            ;;
    esac
    shift
done

