#!/bin/bash

# ------------
# Check if a given application exists.
#
# @author  Björn Hempel  <bjoern@hempel.li>
# @version 1.0 (2017-05-12)
# ------------
applicationExists()
{
    `which $1 >/dev/null`
}

# ------------
# Returns the content from a given file from line $lineFrom to the first match
# string $matchString or until the end of the file.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-12)
# ------------
getContentFromLineToMatch()
{
    local        file="$1"
    local    lineFrom=$2
    local matchString="$3"
    local  dockerName="$4"

    # check if file exists
    if ! fileExistsLocallyOrOnDocker "$file" "$dockerName"; then
        echo -n "" && return 1
    fi

    # helper variables
    local         lines=0
    local         found=false
    local    serverRoot='/etc/apache2'
    local possibleLines=$(executeLocallyOrOnDocker "cat \"$file\" | tail -n+$lineFrom" "$dockerName")

    possibleLines=$(echo "$possibleLines" | wc -l)

    # try to find the end tag of VirtualHost (</VirtualHost>)
    if [ $possibleLines -gt 0 ]; then
        while ! $found; do
            ((lines++))

            if [ "$dockerName" != "" ]; then
                local content=$(docker exec -it $dockerName cat "$file" | tail -n+$lineFrom | head -n$lines)
            else
                local content=$(tail -n+$lineFrom "$file" | head -n$lines)
            fi

            # $matchString found -> stop here
            [[ "$content" =~ "$matchString" ]] && found=true

            # end of file reached
            [ $lines -ge $possibleLines ] && found=true
        done
    fi

    echo "$content" && return 0
}

# ------------
# Tries to extract the complete virtual host block
# in given file $file on line $lineFrom. The function
# also replaces include commands with the content of
# the that include file. Relative include paths will
# be extended with given $serverRoot path.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-12)
# ------------
getVirtualHost()
{
    shopt -s nocasematch

    local        file="$1"
    local    lineFrom=$2
    local matchString='</VirtualHost>'
    local  serverRoot="$3"
    local  dockerName="$4"

    local content=$(getContentFromLineToMatch "$file" $lineFrom "$matchString" "$dockerName")
    local lastStatus=$?

    # no content found
    if [ $lastStatus -gt 0 ]; then
        echo -n "" && return $lastStatus
    fi

    # replace all "include paths"
    while [[ "$content" =~ (^|$'\n')([[:space:]]*)(include[[:space:]]+)([a-z0-9_/.-]+) ]]; do
        local fullstring="${BASH_REMATCH[3]}${BASH_REMATCH[4]}"
        local includePath="$serverRoot/${BASH_REMATCH[4]}"

        if [ "$dockerName" != "" ]; then
            local includeContent=$(docker exec -it $dockerName cat "$includePath")
        else
            local includeContent=$(cat "$includePath")
        fi

        content=$(echo "${content//$fullstring/$includeContent}")
    done

    echo "$content"
    return 0
}

# ------------
# Tries to extracts the target (document root, proxy target, redirect, etc)
# from given virtual config block in given $file on line $lineFrom.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-23)
# ------------
getTargetFromVirtualHost()
{
    shopt -s nocasematch

    local       file="$1"
    local   lineFrom=$2
    local serverRoot="$3"
    local dockerName="$4"

    local virtualHost=$(getVirtualHost "$file" $lineFrom "$serverRoot" "$dockerName")

    local documentRoot=$(echo "$virtualHost" | grep -i "DocumentRoot" | head -n 1)
    local proxyPass=$(echo "$virtualHost" | grep -i "ProxyPass[ $'\t']" | head -n 1)
    local rewriteRule=$(echo "$virtualHost" | grep -i "RewriteRule" | grep 301 | head -n 1)

    if [ "$documentRoot" != "" ]; then
        if [[ "$documentRoot" =~ ([\t ]*DocumentRoot[\t ]+)([a-z0-9/.-]+) ]]; then
            echo "file://${BASH_REMATCH[2]}"
            return 0
        else
            return 1
        fi
    fi

    if [ "$proxyPass" != "" ]; then
        if [[ "$proxyPass" =~ ([\t ]*ProxyPass[\t ]+[a-z0-9/.-]+[\t ]+)([a-z0-9/.:-]+) ]]; then
            echo "${BASH_REMATCH[2]}"
            return 0
        else
            return 1
        fi
    fi

    if [ "$rewriteRule" != "" ]; then
        local uri=$(echo "$rewriteRule" | awk '{print $3}')

        if [ "$uri" != "" ]; then
            echo "$uri"
            return 0
        else
            return 1
        fi
    fi

    return 1
}

# ------------
# Gets the number of cpus.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-14)
# ------------
getNumberOfCpus()
{
    cat /proc/cpuinfo | grep "processor" | wc -l
}

# ------------
# Gets the ram size in gb.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-14)
# ------------
getRamSizeGb()
{
    free | grep 'Mem:' | awk '{print $2/1024/1024}'
}

# ------------
# Gets the hd size in gb.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-14)
# ------------
getHdSizeGb()
{
    df -h | grep '^/dev/' | grep -v 'boot' | awk '{print $2*1}'
}

# ------------
# Gets the percent of used disc size
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-14)
# ------------
getHdUsedPercent()
{
    df -h | grep '^/dev/' | grep -v 'boot' | awk '{print $5*1}'
}

# ------------
# Gets all users.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-14)
# ------------
getUsers()
{
    cat /etc/passwd | grep ':[0-9]\+:100:' | awk -F: '{ st = index($0,":"); print $1}'
}

# ------------
# Gets the full name of given user.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-23)
# ------------
getFullnameFromUser()
{
    getent passwd "$1" | cut -d ':' -f 5 | cut -d ',' -f 1
}

# ------------
# Gets the php version
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-23)
# ------------
getPhpVersion()
{
    php -v | grep -E "PHP [0-9]" | awk '{print $2}'
}

# ------------
# Gets the mysql version
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-23)
# ------------
getMysqlVersion()
{
    mysql --version | awk '{print $5}' | sed -E 's/,$//'
}

# ------------
# Gets the os name and version.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-14)
# ------------
getOSName()
{
    OS=$(uname -s)
    REV=$(uname -r)
    MACH=$(uname -m)

    if [ "${OS}" = "SunOS" ] ; then
        OS=Solaris
        ARCH=$(uname -p)
        OSSTR="${OS} ${REV}(${ARCH} $(uname -v))"
    elif [ "${OS}" = "AIX" ] ; then
        OSSTR="${OS} $(oslevel) ($(oslevel -r))"
    elif [ "${OS}" = "Linux" ] ; then
        KERNEL=$(uname -r)
        if [ -f /etc/redhat-release ] ; then
            DIST='RedHat'
            PSUEDONAME=$(cat /etc/redhat-release | sed s/.*\(// | sed s/\)//)" "
            REV=$(cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//)
        elif [ -f /etc/SuSE-release ] ; then
            DIST=$(cat /etc/SuSE-release | tr "\n" ' '| sed s/VERSION.*//)
            REV=$(cat /etc/SuSE-release | tr "\n" ' ' | sed s/.*=\ //)
        elif [ -f /etc/mandrake-release ] ; then
            DIST='Mandrake'
            PSUEDONAME=$(cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//)" "
            REV=$(cat /etc/mandrake-release | sed s/.*release\ // | sed s/\ .*//)
        elif [ -f /etc/debian_version ] ; then
            DIST="Debian $(cat /etc/debian_version)"
            REV=""
        fi
        if [ -f /etc/UnitedLinux-release ] ; then
            DIST="${DIST}[$(cat /etc/UnitedLinux-release | tr "\n" ' ' | sed s/VERSION.*//)]"
        fi

        OSSTR="${OS} ${DIST} ${REV}(${PSUEDONAME}${KERNEL} ${MACH})"
    fi

    echo ${OSSTR}
}

# ------------
# Gets the number of updateable applications.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-14)
# ------------
getNumberOfInstallableApplications()
{
    aptitude search '~U' | wc -l
}

# ------------
# Returns the internal ip address.
#
# @author  Björn Hempel
# @version 1.0
# ------------
getInternalIp ()
{
  # get from first ip address
  local ip=$(/sbin/ifconfig | grep -E 'inet (addr|Adresse):' | awk '{print $2}' | sed -E 's/(Adresse|addr)://' | grep -v '127.0.0.1' | head -n 1)

  echo $ip
}

# ------------
# Returns external ip address.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0
# ------------
getExternalIp()
{
    local ip=$(curl -s https://api.ipify.org)

    echo "$ip"
}

# ------------
# Returns a markdown of system informations and document roots.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-14)
# ------------
getMarkdownOfSystemAndDocumentRoots()
{
    if $SHOW_SYSTEM_INFORMATIONS; then
        echo '### System informations'
        echo
        echo '| Name | Value |'
        echo '| ---- | ----- |'
        echo '| document created at | '$(date "+%Y-%m-%d %H:%M:%S")' |'
        echo '| full os name | '$(getOSName)' |'
        echo '| hostname | '$(hostname)' |'
        echo '| number of cpus | '$(getNumberOfCpus)' |'
        echo '| ram size in gb | '$(getRamSizeGb)' |'
        echo '| hd disc size in gb | '$(getHdSizeGb)' |'
        echo '| used hd disc size | '$(getHdUsedPercent)' % |'
        echo '| internal ip address | '$(getInternalIp)' |'
        echo '| external ip address | '$(getExternalIp)' |'
        echo '| number of updateable applications | '$(getNumberOfInstallableApplications)' |'
        echo '| php version | '$(getPhpVersion)' |'
        echo '| mysql version | '$(getMysqlVersion)' |'

        echo
        echo '### Users'
        echo

        echo '| Username | Fullname |'
        echo '| ---- | ----- |'

        local users=$(getUsers)
        while read -r user; do
            local fullname=$(getFullnameFromUser "$user")
            echo "| $user | $fullname |"
        done <<< "$users"

        echo 
    fi

    echo '### Projects'
    echo
    for target in "${!schemeHostsContainer[@]}"; do
        eval "declare -A project="$(analyzeProject "$target")

        echo "- $target"

        readarray -t schemeHosts <<< "${schemeHostsContainer[$target]}"

        local ssl=false

        if [ ${#schemeHosts[@]} -le 1 ]; then
            echo "  - target: ${schemeHosts[0]}"
            [[ "${schemeHosts[0]}" =~ ^https ]] && ssl=true
        else
            echo "  - targets:"
            for schemeHost in "${schemeHosts[@]}"; do
                echo "    - $schemeHost"
                [[ "$schemeHost" =~ ^https ]] && ssl=true
            done
        fi

        echo "  - ssl: "$($ssl && echo 'true' || echo 'false')
        echo "  - app: ${project[app]}"
        echo "  - version: ${project[version]}"
    done
    echo
}

# ------------
# Returns a json of system informations and document roots.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-14)
# ------------
getJsonOfSystemAndDocumentRoots()
{
    echo '{'

    if $SHOW_SYSTEM_INFORMATIONS; then
        echo '    "created-at":                    "'$(date "+%Y-%m-%d %H:%M:%S")'",'
        echo '    "os-name-full":                  "'$(getOSName)'",'
        echo '    "hostname":                      "'$(hostname)'",'
        echo '    "number-of-cpus":                "'$(getNumberOfCpus)'",'
        echo '    "ram-size-gb":                   "'$(getRamSizeGb)'",'
        echo '    "hd-size-gb":                    "'$(getHdSizeGb)'",'
        echo '    "hd-size-used-percent":          "'$(getHdUsedPercent)'",'
        echo '    "internal-ip-address":           "'$(getInternalIp)'",'
        echo '    "external-ip-address":           "'$(getExternalIp)'",'
        echo '    "updateable-application-number": "'$(getNumberOfInstallableApplications)'",'
        echo '    "php-version":                   "'$(getPhpVersion)'",'
        echo '    "mysql-version":                 "'$(getMysqlVersion)'",'

        local users=$(getUsers)
        echo '    "users":                         {'
        local counter=0
        while read -r user; do
            local fullname=$(getFullnameFromUser "$user")
            [ $counter -gt 0 ] && echo ","
            echo -n "                                         \"$user\": \"$fullname\""
            ((counter++))
        done <<< "$users"
        echo
        echo '                                     },'
    fi

    echo '    "projects":                      {'
    local counter=0
    for target in "${!schemeHostsContainer[@]}"; do
        eval "declare -A project="$(analyzeProject "$target")

        [ $counter -gt 0 ] && echo ","
        echo    "                                         \"$target\": {"
        echo    "                                             \"domains\": ["

        readarray -t schemeHosts <<< "${schemeHostsContainer[$target]}"
        local ssl=false

        local counter2=0
        for schemeHost in "${schemeHosts[@]}"; do
            [ $counter2 -gt 0 ] && echo ","
            echo -n "                                                 \"$schemeHost\""
            ((counter2++))

            [[ "$schemeHost" =~ ^https ]] && ssl=true
        done
        echo
        echo    "                                             ],"
        echo    "                                             \"ssl\": "$($ssl && echo 'true' || echo 'false')","
        echo    "                                             \"app\": \"${project[app]}\","
        echo    "                                             \"version\": \"${project[version]}\""
        echo -n "                                         }"
        ((counter++))
    done
    echo
    echo '                                     }'
    echo '}'
}

# ------------
# Compress given json string.
#
# @author  Björn Hempel
# @version 1.0 (2017-05-05)
# ------------
compressJson()
{
    local json="$1"

    echo -n "$json" | sed 's/^[ \t]*//' | sed ':a;N;$!ba;s/\n//g' | sed 's/:[ ]\+"/:"/g' | sed 's/:[ ]\+\[/:\[/g' | sed 's/:[ ]\+{/:{/g'
}

# ------------
# Converts the given md file into a html file.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-28)
# ------------
md2html()
{
    local  markdownContent="$1"
    local          cssFile="${2:-markdown.css}"
    local       servername=$(hostname)
    local markdown2HtmlApp="markdown"
    local        tmpMdFile=$(mktemp)

    # check if markdown app exists
    if ! applicationExists "$markdown2HtmlApp"; then
        >&2 echo "Application $markdown2HtmlApp does not exist on this system. Please install with:"
        >&2 echo
        >&2 echo "user$ curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -"
        >&2 echo "user$ sudo apt install nodejs"
        >&2 echo "user$ sudo npm install markdown-to-html -g"
        return 2
    fi

    # markdown html before
    read -d '' head <<EndOfMessage
<!DOCTYPE html>
<html lang="en">
    <head>
        <!--[if IE]>                                                                                                                                                   
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charset="UTF-8" />
        <title>$servername</title>
        <link rel="stylesheet" href="$cssFile">
        <style>
            .markdown-body {
                box-sizing: border-box;
                min-width: 200px;
                max-width: 980px;
                margin: 0 auto;
                padding: 45px;
            }
        </style>
    </head>
    <body>
        <article class="markdown-body">
EndOfMessage

    # markdown html after
    read -d '' footer <<EndOfMessage
        </article>
    </body>
</html>
EndOfMessage

    # create temporary md file
    echo "$markdownContent" > "$tmpMdFile"

    # some changes with markdown
    content=$(markdown "$tmpMdFile" -h)
    # | sed -e 's/<table>/<table style="width:100%;">/g')

    # remove temp markdown file
    rm "$tmpMdFile"

    # write html index file
    echo "$head"
    echo "$content"
    echo "$footer"

    # return 0
    return 0
}

# ------------
# Converts the given md file into a html file.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-28)
# ------------
md2htmlFile()
{
    local markdownFile="$1"
    local    indexFile="$2"
    local   targetPath=$(dirname "$indexFile")

    local          cssFile="https://raw.githubusercontent.com/sindresorhus/github-markdown-css/gh-pages/github-markdown.css"
    local          cssName="markdown.css"
    local      cssFullpath="$targetPath/$cssName"

    # download css file
    wget -O "$cssFullpath" --quiet "$cssFile"

    # check css file
    if [ ! -f "$cssFullpath" ]; then
        echo "It was not able to download the css file \"$cssFullpath\"."
        return 1
    fi

    # convert the markdown content into html content
    markdownContent=$(cat "$markdownFile")
    htmlContent=$(md2html "$markdownContent" "$cssName")

    # write html index file
    echo "$htmlContent" > $indexFile

    # return 0
    return 0
}


# ------------
# Analyzes the given project path and tries to find out the app and version number.
#
# @author  Björn Hempel
# @version 1.0 (2017-05-23)
# ------------
analyzeProject()
{
    local uri="$1"

    local scheme=""
    local   path="$uri"

    local     app='unknown'
    local version='unknown'

    # the return array
    declare -A ret=()

    # check the uri
    if [[ "$uri" =~ ^([a-z]+)://(.+) ]]; then
        scheme="${BASH_REMATCH[1]}"
        path="${BASH_REMATCH[2]}"
    fi

    # redirection or proxy-pass
    if [[ "$scheme" =~ ^http ]]; then
            ret[app]='redirection'
        ret[version]='not available'

        local retDeclare=$(declare -p ret)

        echo "${retDeclare#*=}"
        return 0
    fi

    # path does not exist
    if [ ! -d "$path" ]; then
        # return array¬
        declare -A ret=()
            ret[app]='not available'
        ret[version]='not available'

        local retDeclare=$(declare -p ret)

        echo "${retDeclare#*=}"
        return 1
    fi

    # some vars
    local projectPath="$path"
    local  startPath=$(pwd)
    cd "$projectPath"

    # contao
    if [ "$app" == "unknown" ] && [ -d "contao" ] && [ -f "system/config/constants.php" ]; then
        app='Contao'
        version=$(php -r 'include_once "system/config/constants.php"; echo VERSION;')
    fi

    # symfony
    if [ "$app" == "unknown" ] && [ -f "app.php" ] && [ -d "../app" ]; then
        cd ..
    fi
    if [ "$app" == "unknown" ] && [ -d "app" ] && [ -f "app/console" ]; then
        app='Symfony'
        version=$(app/console --version | awk '{print $3}' | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g")
    fi

    # TYPO3
    if [ "$app" == "unknown" ] && ([ -d "typo3_src/typo3" ] || [ -d "typo3" ]); then
        app='TYPO3'
        version="unknown"

        local typo3src=""
        [ -d "typo3_src/typo3" ] && typo3src="typo3_src/typo3"
        [ -d "typo3"           ] && typo3src="typo3"

        pathSystemEnvironmentBuilder="$typo3src/sysext/core/Classes/Core/SystemEnvironmentBuilder.php"
        if [ -f "$pathSystemEnvironmentBuilder" ]; then
            version=$([[ $(grep --no-filename -r "define('TYPO3_version'" "$pathSystemEnvironmentBuilder") =~ TYPO3_version\',[[:space:]]*\'([^\']*) ]] && echo ${BASH_REMATCH[1]})
        fi
    fi

    # Wordpress
    if [ "$app" == "unknown" ] && [ -d "wordpress" ]; then
        cd "wordpress"
    fi
    if [ "$app" == "unknown" ] && [ -d "wp-admin" ]; then
        app='Wordpress'
        version='unknown'

        versionFile='wp-includes/version.php'
        if [ -f "$versionFile" ]; then
            version=$([[ $(grep --no-filename -r "\$wp_version =" "$versionFile") =~ wp_version[[:space:]]*=[[:space:]]*\'([^\']*) ]] && echo ${BASH_REMATCH[1]})
        fi
    fi

    # Dresden Frontend Tool
    if [ "$app" == "unknown" ] && [ -d "dd-fe-tool" ]; then
        app='DD Frontend Tool (Silex)'

        cd "dd-fe-tool"

        versionFile='vendor/silex/silex/src/Silex/Application.php'
        if [ -f "$versionFile" ]; then
            version=$([[ $(grep --no-filename -r "VERSION =" "$versionFile") =~ VERSION[[:space:]]*=[[:space:]]*\'([^\']*) ]] && echo ${BASH_REMATCH[1]})
        fi
    fi

    # index.php
    if [ "$app" == "unknown" ] && [ -f "index.php" ]; then
        app='PHP project'
        version='PHP '$(php -v | grep -E "PHP [0-9]" | awk '{print $2}')
    fi

    # index.html
    if [ "$app" == "unknown" ] && [ -d "html" ]; then
        cd "html"
    fi
    if [ "$app" == "unknown" ] && [ -f "index.html" ]; then
        app='HTML project'
        version='unknown'
    fi

    # return array
    declare -A ret=()
        ret[app]="$app"
    ret[version]="$version"

    # return the array
    local retDeclare=$(declare -p ret)
    echo "${retDeclare#*=}"

    # save start path
    cd "$startPath"

    return 0
}

# ------------
# check if a given application exists
#
# @author  Björn Hempel
# @version 1.0
# ------------
applicationExists() {
  `which $1 >/dev/null`
}

