#!/bin/bash

# declare parameter list array
PARAMETERS=()

# default parameter
MARKDOWN_OUTPUT=true
JSON_OUTPUT=false
HTML_OUTPUT=false
COMPRESS_JSON=false
SHOW_SYSTEM_INFORMATIONS=false
SHOW_LINKS=false
DOCKER_NAME=""
PARSE_VHOSTS=true
OUTPUT_TARGET=""
OUTPUT_NAME="index"
CREATE_JSON=false
CREATE_MARKDOWN=true
CREATE_HTML=false
MARKDOWN_SUFFIX="md"
JSON_SUFFIX="json"
HTML_SUFFIX="html"
SILENCE=false

# read arguments
# help:
# help: Usage: %scriptname% [options...]
while [[ $# > 0 ]]; do
    case "$1" in
        # help:  -h,    --help                    Shows this help.
        -h|--help)
            cat "$pathRoot/lib/parameter" | grep "# help:" | grep -v 'cat parameter' | sed 's/[ ]*# help:[ ]\?//g' | sed "s~%scriptname%~$scriptname~g"
            exit 0
            ;;

        # help:
        # help:  -m,    --markdown                Shows the output as markdown and disable all other output types (json, html) - default output
        -m|--markdown)
            MARKDOWN_OUTPUT=true
                JSON_OUTPUT=false
                HTML_OUTPUT=false
            ;;

        # help:  -j,    --json                    Shows the output as json and disable all other output types (markdown, html)
        -j|--json)
            MARKDOWN_OUTPUT=false
                JSON_OUTPUT=true
                HTML_OUTPUT=false
            ;;

        # help:         --html                    Shows the output as html and disable all other output types (markdown, json)
        --html)
            MARKDOWN_OUTPUT=false
                JSON_OUTPUT=false
                HTML_OUTPUT=true
            ;;

        # help:         --compress-json           Compress the outputted json.
        --compress-json)
            COMPRESS_JSON=true
            ;;

        # help:
        # help:         --output-target           Writes also the result into this target folder.
        --output-target)
            OUTPUT_TARGET="$2"
            shift
            ;;
        --output-target=*)
            OUTPUT_TARGET="${1#*=}"
            ;;

        # help:         --output-name             Set the output name (default is "index").
        --output-name)
            OUTPUT_NAME="$2"
            shift
            ;;
        --output-name=*)
            OUTPUT_NAME="${1#*=}"
            ;;

        # help:         --create-markdown         Creates a markdown file (--output-target must be set).
        --create-markdown)
            CREATE_MARKDOWN=true
            ;;
        --create-markdown=*)
            [ "${1#*=}" == "0" ] && CREATE_MARKDOWN=false || CREATE_MARKDOWN=true
            ;;

        # help:         --create-json             Creates a json file (--output-target must be set).
        --create-json)
            CREATE_JSON=true
            ;;
        --create-json=*)
            [ "${1#*=}" == "0" ] && CREATE_JSON=false || CREATE_JSON=true
            ;;

        # help:         --create-html             Creates a html file (--output-target must be set).
        --create-html)
            CREATE_HTML=true
            ;;
        --create-html=*)
            [ "${1#*=}" == "0" ] && CREATE_HTML=false || HTML_MARKDOWN=true
            ;;

        # help:
        # help:  -s,    --show-system-info        Shows system informations.
        -s|--show-system-info)
            SHOW_SYSTEM_INFORMATIONS=true
            ;;

        # help:         --show-links              Shows links inside the markdown and html file
        --show-links)
            SHOW_LINKS=true
            ;;

        # help:
        # help:  -d,    --docker-container        Checks a docker machine instead of the local machine.
        -d|--docker-container)
            DOCKER_NAME="$2"
            shift
            ;;
        -d=*|--docker-container=*)
            DOCKER_NAME=("${1#*=}")
            ;;

        # help:
        # help:         --disable-vhost-parser    Disable the vhost parser.
        --disable-vhost-parser)
            PARSE_VHOSTS=false
            ;;

        # help:
        # help:         --silence                 Disable the output.
        --silence)
            SILENCE=true
            ;;

        # help:
        #
        # collect all unknown parameters
        #
        *)
            PARAMETERS+=("$1")
            ;;
    esac
    shift
done

