#!/bin/bash

# declare parameter list array
PARAMETERS=()

# default parameter
JSON_OUTPUT=false
COMPRESS_JSON=false
MARKDOWN_OUTPUT=true
SHOW_SYSTEM_INFORMATIONS=false
DOCKER_NAME=""
PARSE_VHOSTS=true

# read arguments
# help:
# help: Usage: %scriptname% [options...]
while [[ $# > 0 ]]; do
    case "$1" in
        # help:  -h,    --help                    Shows this help.
        # help:
        -h|--help)
            cat "$pathRoot/lib/parameter" | grep "# help:" | grep -v 'cat parameter' | sed 's/[ ]*# help:[ ]\?//g' | sed "s~%scriptname%~$scriptname~g"
            exit 0
            ;;

        # help:  -j,    --json                    Shows the output as json and disable the markdown output
        # help:
        -j|--json)
            JSON_OUTPUT=true
            MARKDOWN_OUTPUT=false
            ;;

        # help:         --compress-json           Compress the outputted json.
        # help:
        --compress-json)
            COMPRESS_JSON=true
            ;;

        # help:  -s,    --show-system-info        Shows system informations.
        # help:
        -s|--show-system-info)
            SHOW_SYSTEM_INFORMATIONS=true
            ;;

        # help:  -d,    --docker-container        Checks a docker machine instead of the local machine.
        # help:
        -d|--docker-container)
            DOCKER_NAME="$2"
            shift
            ;;
        -d=*|--docker-container=*)
            DOCKER_NAME=("${1#*=}")
            ;;

        # help:         --disable-vhost-parser    Disable the vhost parser.
        # help:
        --disable-vhost-parser)
            PARSE_VHOSTS=false
            ;;

        #
        # collect all unknown parameters
        #
        *)
            PARAMETERS+=("$1")
            ;;
    esac
    shift
done
